オプション課題 Rspec修正、let, traitの利用
akitoshi-m/rspec_app_exam pull request #1
Opened 2020-04-27 15:20 UTC by Toshimatu

## 概要、行った修正

【やったこと】
・リポジトリをfork
・git cloneしディレクトリ移動
・任意のブランチ名でcheckout

【修正したテストの修正事項】
■it 'Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること' 
![Project詳細ページにとどまっている為](https://user-images.githubusercontent.com/52368204/80389266-d6272780-88e5-11ea-9f51-a95670c05055.png)

Project詳細ページから"View Todos"を押下すると新しいタブでページが開かれる為、テスト側で遷移先を指定する必要があった。テストしているページが違った為、生じたエラー。

![URLにtaskのデータが渡されていなかった為](https://user-images.githubusercontent.com/52368204/80389324-dfb08f80-88e5-11ea-8a44-b60cd837de7f.png)

URLにtaskのデータが渡されていなかった為、引数にtaskを渡した。

■it 'Taskを編集した場合、一覧画面で編集後の内容が表示されること' 

![時間表記の違いによるテスト失敗の画像](https://user-images.githubusercontent.com/52368204/80389396-fb1b9a80-88e5-11ea-99c8-48b055878793.png)

時間の表記のしかたの違いによるもの。strf関数を調べ、期待する表記に修正。
修正後　%-m/%d %H:%M
・「-」をつけることで0埋めさせないようにする

■it 'Taskが削除されること' 
![URLにtaskのデータが渡されていなかった為](https://user-images.githubusercontent.com/52368204/80389133-a9731000-88e5-11ea-8936-2875cc0ff10f.png)

・タスク一覧ページに遷移した先にtaskのデータがなかった→taskを渡すことで解決

![task titleは Task であり、flashメッセージに同じ文字が現れる為NG](https://user-images.githubusercontent.com/52368204/80389212-c0b1fd80-88e5-11ea-8c51-b0a40a48b14f.png)

・task.titleが表示されていないことを確認するテストだが、task.titleの中身は"Task"であり、タスクを削除した際に表示される"
Task was successfully destroyed."のなかに"Task"の文字が含まれる為テストが成り立たない。
→taskファクトリのtitleを修正

## 確認方法

1. gemを追加したので `bundle exec bundle install` を実行してください
2. `rspec spec/system/task_spec.rb`を実行しテスト結果を確認してください。

## チェックリスト

- [x] siderをパスした

## コメント

2020-04-28 02:16 UTC, yuji91 requested changes

2020-04-28 02:16 UTC, yuji91 commented on spec/system/task_spec.rb
> +        visit project_tasks_path(project, task)
visitでも出来ますが「新しく開いたタブに切り替える」というコードがあるのでそちらを使ってみましょう！

2020-04-28 02:16 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %H:%M'))
こちらの時刻変更の処理ですが、view側で使用しているメソッドがあるのでそれを呼び出す形にしましょう。
メソッドで表示する仕様が変わってもテストが失敗しないようにしたいです。

2020-04-28 02:16 UTC, yuji91 commented on spec/factories/tasks.rb
> +    title { 'ExampleTask' }
Factoryを変更してテストが失敗しないようにしていると思いますが、テストの内容とFactoryで指定している値に依存性が出来ています。
テスト対象の画面をブラウザの検証ツールで開いて、どう修正するのが良いかを考えてみてください。
`it 'Taskを編集した場合、一覧画面で編集後の内容が表示されること'`のテストケースにヒントがあります。

2020-04-28 14:54 UTC, Toshimatu commented on spec/system/task_spec.rb
> +        visit project_tasks_path(project, task)
c36b754 にて修正しました。

2020-04-28 14:54 UTC, Toshimatu commented on spec/factories/tasks.rb
> +    title { 'ExampleTask' }
b6d8dcc ( cabf5f0 )にて修正しました。

2020-04-28 14:54 UTC, Toshimatu commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %H:%M'))
94e2346 にて修正しました。

2020-04-29 01:09 UTC, yuji91 requested changes

2020-04-29 01:09 UTC, yuji91 commented on spec/system/task_spec.rb
> +  include ApplicationHelper
ここに記載してもいいですが、他でも使いそうであれば rails_helper や spec_helper などの設定ファイルで読み込むことも可能です。

2020-04-29 01:50 UTC, Toshimatu commented on spec/system/task_spec.rb
> +  include ApplicationHelper
361d8ff にて修正しました。

![image](https://user-images.githubusercontent.com/52368204/80554162-32ce3380-8a07-11ea-824e-ad395259c3c2.png)

2020-04-29 01:53 UTC, yuji91 approved these changes

2020-04-29 02:23 UTC, merged